@Styles function xq_m(){
  .margin(15)
}
// 距离顶部
@Styles function xq_mt_xs(){
  .margin({top:5})
}

@Styles function xq_mt_sm(){
  .margin({top:10})
}
@Styles function xq_mt_lg(){
  .margin({top:20})
}
@Styles function xq_mt_xl(){
  .margin({top:25})
}

//距离左侧
@Styles function xq_ml_xs(){
  .margin({left:5})
}

@Styles function xq_ml_sm(){
  .margin({left:10})
}
@Styles function xq_ml_lg(){
  .margin({left:20})
}
@Styles function xq_ml_xl(){
  .margin({left:25})
}

//距离右侧
@Styles function xq_mr_xs(){
  .margin({right:5})
}

@Styles function xq_mr_sm(){
  .margin({right:10})
}
@Styles function xq_mr_lg(){
  .margin({right:20})
}
@Styles function xq_mr_xl(){
  .margin({right:25})
}

//距离底部
@Styles function xq_mb_xs(){
  .margin({bottom:5})
}

@Styles function xq_mb_sm(){
  .margin({bottom:10})
}
@Styles function xq_mb_lg(){
  .margin({bottom:20})
}
@Styles function xq_mb_xl(){
  .margin({bottom:25})
}