@Styles function xq_p(){
  .padding(15)
}
// 距离顶部
@Styles function xq_pt_xs(){
  .padding({top:5})
}

@Styles function xq_pt_sm(){
  .padding({top:10})
}
@Styles function xq_pt_lg(){
  .padding({top:20})
}
@Styles function xq_pt_xl(){
  .padding({top:25})
}

//距离左侧
@Styles function xq_pl_xs(){
  .padding({left:5})
}

@Styles function xq_pl_sm(){
  .padding({left:10})
}
@Styles function xq_pl_lg(){
  .padding({left:20})
}
@Styles function xq_pl_xl(){
  .padding({left:25})
}

//距离右侧
@Styles function xq_pr_xs(){
  .padding({right:5})
}

@Styles function xq_pr_sm(){
  .padding({right:10})
}
@Styles function xq_pr_lg(){
  .padding({right:20})
}
@Styles function xq_pr_xl(){
  .padding({right:25})
}

//距离底部
@Styles function xq_pb_xs(){
  .padding({bottom:5})
}

@Styles function xq_pb_sm(){
  .padding({bottom:10})
}
@Styles function xq_pb_lg(){
  .padding({bottom:20})
}
@Styles function xq_pb_xl(){
  .padding({bottom:25})
}