@Observed
export default class KnowledgeItem {
  id: number = 0;
  subPicBottom: string = '';
  titleIcon: string = '';
  title: string = '';
  subTitle: string = '';
  thumbnail: string = '';
  swiperPic: string = '';
  createTime: string = '';
  subPicTop: string = '';
  buildingInformation: string = '';
  buildingPic: string = '';
  geographyPic: string = '';
  geographyPicLight: string = '';
  backgroundColor: string = '';
  content: string[] = [];
  imageList: string[] = [];
  starLinePic: string[] = [];
}